#!/bin/bash

echo $SSH_PRIVATE_KEY
which ssh-agent || ( apt-get install -qq openssh-client )
eval $(ssh-agent -s)
ssh-add <(echo "$SSH_PRIVATE_KEY")
mkdir -p ~/.ssh 2>/dev/null
echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config
echo -e "Host deploy\n${SSH_HOST_CONFIG}" >> ~/.ssh/config
./make/rsyncandstart
