#!/bin/bash

DEPLOYDIR=${DEPLOYDIR:-"/app"}
CI="$HOME/projects/ci-extend"
dockerfile="$CI/Dockerfile"

# Just copy env is enough, use in CI
cp ./.en* $CI/

docker image build -t ${CI_IMAGE} -f ${dockerfile} --build-arg DEPLOYDIR="$DEPLOYDIR" --build-arg MYAPP_IMAGE="${MYAPP_IMAGE}" --build-arg HOST_SSH_PRIVATE="$HOST_SSH_PRIVATE" --build-arg SSH_HOST_CONFIG="$SSH_HOST_CONFIG" --build-arg HOST_SSH_PUBLIC="$HOST_SSH_PUBLIC" $CI
# cmd="docker container run $EXTRARUNDOCKER -d --name $INSTANCE ${CI_IMAGE} $EXTRARUNDOCKERAFTER"
# eval $cmd
# echo $cmd
cmd="docker save ${CI_IMAGE} | gzip > image.tar.gz"
echo $cmd
cmd="echo rsync image.tar target:/tmp/image.tar.gz and ssh to target"
echo $cmd
cmd="docker load < /tmp/image.tar.gz"
echo $cmd
