#!/bin/bash

# Store all environments
pwd
DEPLOYDIR=${DEPLOYDIR:-"${PWD}"}
mkdir -p $DEPLOYDIR
cd $DEPLOYDIR
ls -la ./
( set -o posix ; set ) | grep -vE "BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID|HOME" > ./.deploy
source ./.deploy
source ./.env
source ~/.bashrc

# Common variables
export DEBIAN_FRONTEND="noninteractive"

NVM_DIR="/usr/local/nvm"
NODE_VERSION=${NODE_VERSION:-"10.24.1"}
echo "Installing node: $NODE_VERSION"
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash

# Install nvm with node, npm, yarn
source ~/.bashrc
nvm install v$NODE_VERSION
nvm use --delete-prefix v$NODE_VERSION
nvm alias default $NODE_VERSION
npm i -g yarn
yarn global add git+https://github.com/oliverhuynh/ci-extend.git -f --prefix /usr/local

# Prepare ci-extend and needed packages
# NM=$(npm root -g)
NM=/usr/local/share/.config/yarn/global/node_modules
# $NM/ci-extend/make/variables
echo "Reinstall node_modules"
rm -rf node_modules

# Libs setup
yarn install
yarn global add sass
yarn global add webpack-cli

apt-get update
apt-get install -y gettext-base rsync libssl-dev

# Git setup
git config --global core.pager "less -d"


# SSH setup
which ssh-agent || (apt-get install -qq openssh-client)

