#!/bin/bash

. ./.deploy
. ~/.bashrc

PARENTDIR=$(dirname $DEPLOYDIR)

if [[ "${DEPLOYDIR}" == "" || "${PARENTDIR}" == "" || "${WORKINGDIR}" == "" || "${RELOADCOMMAND}" == "" ]]; then
  echo "Please write a proper DEPLOYDIR, PARENTDIR, WORKINGDIR, RELOADCOMMAND"
  exit 1
fi
rsync -ravz --rsync-path="sudo rsync" $RSYNCMORE --delete $WORKINGDIR deploy:$PARENTDIR/

# rsync -ravz --delete . deploy:$DEPLOYDIR/
if [[ "$DEPLOYNOUSENVM" != "" ]]; then
  ssh deploy 'bash -c "cd '$DEPLOYDIR' && '$RELOADCOMMAND'"'
else
  ssh deploy 'bash -c "export NVM_DIR=\"\$HOME/.nvm\" && \. \"\$NVM_DIR/nvm.sh\" && nvm install '$NODEVERSION' && nvm use '$NODEVERSION' && cd '$DEPLOYDIR' && '$RELOADCOMMAND'"; sudo nginx -t && sudo service nginx reload'
fi
