#!/bin/bash

( set -o posix ; set ) | grep -vE "BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID|HOME" > ./.deploy
. ./.deploy
. ~/.bashrc

# SSH VARIABLES
mkdir -p ~/.ssh
# echo "Setting up:$HOST_SSH_PUBLIC. $SSH_HOST_CONFIG"
echo "$HOST_SSH_PUBLIC" >~/.ssh/id_rsa.pub
echo "$HOST_SSH_PRIVATE" >~/.ssh/id_rsa
printf "Host *\n\tStrictHostKeyChecking no\n\n" >>~/.ssh/config
chmod 600 ~/.ssh/*
[[ "$HOST_PREPARE" != "" ]] && eval $HOST_PREPARE
ssh-keyscan -t rsa github.com >>~/.ssh/known_hosts
printf "Host deploy\n${SSH_HOST_CONFIG}" >>~/.ssh/config

# GIT SUBMODULES, RESOURCES READY
git submodule update --init --recursive --remote
git submodule sync --recursive
source ~/.bashrc
yarn install

# Env setup
cp ./.env.$APP_ENV ./.env && cp ./.env.more.$APP_ENV ./.env.more
