#!/bin/bash

export >.deploy
apt-get update
apt-get install -y gettext-base rsync libssl-dev
mkdir -p ~/.ssh
echo "Setting up:$HOST_SSH_PUBLIC. $SSH_HOST_CONFIG"
echo "$HOST_SSH_PUBLIC" >~/.ssh/id_rsa.pub
echo "$HOST_SSH_PRIVATE" >~/.ssh/id_rsa
printf "Host *\n\tStrictHostKeyChecking no\n\n" >>~/.ssh/config
chmod 600 ~/.ssh/*
which ssh-agent || (apt-get install -qq openssh-client)
ssh-keyscan -t rsa github.com >>~/.ssh/known_hosts
printf "Host deploy\n${SSH_HOST_CONFIG}" >>~/.ssh/config
git submodule update --init --recursive --remote
git submodule sync --recursive
npm install
